<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TRUEXAMINE — {{ $report['ams_ref'] ?? 'Report' }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #111; line-height: 1.35; }
        h1 { font-size: 14pt; margin: 0 0 4pt 0; }
        h2 { font-size: 11pt; margin: 14pt 0 6pt 0; border-bottom: 1pt solid #333; padding-bottom: 2pt; }
        .meta { font-size: 9pt; margin-bottom: 12pt; }
        .badge { display: inline-block; padding: 2pt 6pt; font-weight: bold; font-size: 9pt; margin-top: 4pt; }
        .red { background: #b91c1c; color: #fff; }
        .yellow { background: #d97706; color: #000; }
        .green { background: #047857; color: #fff; }
        .muted { color: #444; }
        table { width: 100%; border-collapse: collapse; margin-top: 6pt; font-size: 9pt; }
        th, td { border: 0.5pt solid #999; padding: 4pt 5pt; vertical-align: top; text-align: left; }
        th { background: #f0f0f0; font-weight: bold; }
        ul { margin: 6pt 0 0 14pt; padding: 0; }
        li { margin-bottom: 3pt; }
        .remarks { white-space: pre-wrap; }
        .disclaimer { font-size: 7pt; color: #555; margin-top: 18pt; border-top: 0.5pt solid #ccc; padding-top: 8pt; }
    </style>
</head>
<body>
    <h1>{{ e($report['vendor_name'] ?? '') }}</h1>
    <p class="meta muted">
        Order date: {{ e($report['order_date'] ?? '') }} &nbsp;|&nbsp;
        Verified date: {{ e($report['verified_date'] ?? '') }}
    </p>
    <p><strong>Client:</strong> {{ e($report['client_name'] ?? '') }}</p>
    <p><strong>Client ref:</strong> {{ e($report['client_ref'] ?? '') }} &nbsp;|&nbsp;
        <strong>AMS ref:</strong> {{ e($report['ams_ref'] ?? '') }}</p>
    @php
        $color = strtoupper($report['report_color'] ?? '');
        $badgeClass = 'green';
        if (str_contains($color, 'RED')) {
            $badgeClass = 'red';
        } elseif (str_contains($color, 'YELLOW') || str_contains($color, 'AMBER')) {
            $badgeClass = 'yellow';
        }
    @endphp
    <p><strong>Report status:</strong>
        <span class="badge {{ $badgeClass }}">{{ e($report['report_color'] ?? '') }}</span>
    </p>

    <h2>GLOBAL DATABASE CHECK — Applicant</h2>
    <table>
        <tr><th style="width:22%">Field</th><th>Value</th></tr>
        <tr><td>Name</td><td>{{ e($report['applicant_name'] ?? '') }}</td></tr>
        <tr><td>Date of birth</td><td>{{ e($report['applicant_dob'] ?? '') }}</td></tr>
        <tr><td>Country (given)</td><td>{{ e($report['applicant_country_given'] ?? '') }}</td></tr>
        <tr><td>Country (verified)</td><td>{{ e($report['applicant_country_verified'] ?? '') }}</td></tr>
    </table>

    <h2>Verification checks</h2>
    <table>
        <thead>
            <tr>
                <th>Check name</th>
                <th>Type of search</th>
                <th>Given</th>
                <th>Verified</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report['verification_checks'] ?? [] as $row)
                <tr>
                    <td>{{ e($row['check_name'] ?? '') }}</td>
                    <td>{{ e($row['type_of_search'] ?? '') }}</td>
                    <td>{{ e($row['given'] ?? '') }}</td>
                    <td>{{ e($row['verified'] ?? '') }}</td>
                    <td>{{ e($row['check_result'] ?? '') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Research</h2>
    <p><strong>Contact method:</strong> {{ e($report['research_contact_method'] ?? '') }}</p>
    <p><strong>Result of verification:</strong> {{ e($report['research_verification_result'] ?? '') }}</p>
    <p><strong>Remarks:</strong></p>
    <p class="remarks">{{ e($report['research_remarks'] ?? '') }}</p>

    <h2>Key findings</h2>
    <ul>
        @foreach($report['key_findings'] ?? [] as $finding)
            <li>{{ e($finding) }}</li>
        @endforeach
    </ul>

    <h2>Verifier</h2>
    <table>
        <tr><th style="width:28%">Field</th><th>Value</th></tr>
        <tr><td>Verifier name</td><td>{{ e($report['verifier_name'] ?? '') }}</td></tr>
        <tr><td>Verifier designation</td><td>{{ e($report['verifier_designation'] ?? '') }}</td></tr>
        <tr><td>Verifier e-mail</td><td>{{ e($report['verifier_email'] ?? '') }}</td></tr>
        <tr><td>Verifier phone</td><td>{{ e($report['verifier_phone'] ?? '') }}</td></tr>
    </table>

    <p class="disclaimer">
        This document was generated by the application from AI-extracted structured data. It is confidential and intended only for authorized recipients.
        Use in compliance with applicable laws and your organization’s screening policies.
    </p>
</body>
</html>
